# Generated by Django 4.0.3 on 2022-03-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=255)),
                ('message_id', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=4000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
