# Generated by Django 4.0.3 on 2022-03-10 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='message_id',
        ),
    ]
