# Generated by Django 4.0.3 on 2022-03-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_channel_id_remove_task_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, '作業中'), (1, '完了'), (2, '失敗')], default=0),
        ),
    ]
