# Generated by Django 4.0.3 on 2022-03-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, '作業中'), (1, '完了'), (2, '失敗')], default=0, editable=False),
        ),
    ]
