# Generated by Django 4.0.3 on 2022-03-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
