# Generated by Django 4.0.3 on 2022-03-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
