# Generated by Django 4.0.3 on 2022-03-13 07:34

from django.db import migrations, models
import functools
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_api_key_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(default=functools.partial(secrets.token_hex, *(64,), **{}), max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
